vich_uploader:
    db_driver: orm
    mappings:
        content_documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: course.id
